ALTER TABLE contact
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED',
    ADD COLUMN mail_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    ADD COLUMN mail_error_message TEXT,
    ADD COLUMN mail_sent_at TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
